name: covid19
channels:
  - conda-forge
dependencies:
  - descartes=1.1.0
  - lxml=4.6.3
  - matplotlib=3.1.3
  - pandas=1.0.3
  - pip=20.0
  - python=3.7.6
  - geopandas=0.8.1
  - seaborn=0.11.1
  - pycountry==20.7.3
  - pip:
    - git+https://github.com/manubot/manubot@a57ccf0be6972329ff3010eaaa0c5df7ccebb2d5
    - wget==3.2
